old=cd('./fig_1');
save('Current_directory','old');
fig_1
fig_S1
load('Current_directory','old');
cd(old)
delete('Current_directory')
%%
old=cd('./fig_2');
save('Current_directory','old');
fig_2
fig_S2
load('Current_directory','old');
cd(old)
delete('Current_directory')
%%
old=cd('./fig_3');
save('Current_directory','old');
fig_3
fig_S3
load('Current_directory','old');
cd(old)
delete('Current_directory')
%%
old=cd('./fig_4');
save('Current_directory','old');
fig_4
fig_S4
load('Current_directory','old');
cd(old)
delete('Current_directory')
%%
old=cd('./fig_5');
save('Current_directory','old');
fig_5
fig_S5
load('Current_directory','old');
cd(old)
delete('Current_directory')
%%
old=cd('./tab_2');
save('Current_directory','old');
tab_2
load('Current_directory','old');
cd(old)
delete('Current_directory')
clear